// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHBzwL-K5GYKLe-zEb8zOjGo5w4mZXSVg',
    appId: '1:545585119000:web:d4a24bd596cefeaf6aa86d',
    messagingSenderId: '545585119000',
    projectId: 'anturus-cc891',
    authDomain: 'anturus-cc891.firebaseapp.com',
    storageBucket: 'anturus-cc891.appspot.com',
    measurementId: 'G-LCDE5XE5NP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf0AU8MAbJCjOuGDeXo-0UuSxmNQ8wExA',
    appId: '1:545585119000:ios:ee10e7f8df9dd1956aa86d',
    messagingSenderId: '545585119000',
    projectId: 'anturus-cc891',
    storageBucket: 'anturus-cc891.appspot.com',
    iosClientId: '545585119000-p2un2v0vqnp3s1q2vhn7cu37jo6bnl9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.anturus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf0AU8MAbJCjOuGDeXo-0UuSxmNQ8wExA',
    appId: '1:545585119000:ios:ee10e7f8df9dd1956aa86d',
    messagingSenderId: '545585119000',
    projectId: 'anturus-cc891',
    storageBucket: 'anturus-cc891.appspot.com',
    iosClientId: '545585119000-p2un2v0vqnp3s1q2vhn7cu37jo6bnl9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.anturus',
  );
}
